# Generated by Django 4.2 on 2025-03-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_gateway'),
        ('food', '0003_alter_restorant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.gateway'),
            preserve_default=False,
        ),
    ]
